### ISSUE TITLE
能否公布一下代码？

### ISSUE THREAD

**Issue by weiSENshu** [mayubo2333/fewshot_ED#1]
您好，请问能发布一下模型的代码吗？

**Comment by mayubo2333** [comment]
您好，感谢您对我们工作的兴趣！我们将在本月内开源代码

**Comment by pkseeg** [comment]
Sounds good. Thank you for your help!

- Parker

**Comment by weiSENshu** [comment]
您好，请问大概什么时候能开源一下代码？我非常想了解一下模型的实现细节，万分感谢！

**Comment by mayubo2333** [comment]
我们已经将代码的核心部分开源（可运行）
我们会尽快整理好剩余部分的代码并开源
