### ISSUE TITLE
使用MAVEN数据集运行时出现AssertionError

### ISSUE THREAD

**Issue by weiSENshu** [mayubo2333/fewshot_ED#2]
```
 tok_embeddings.shape[0]: 97315
event_feature_num 97309
Traceback (most recent call last):
  File "main.py", line 546, in <module>
    main()
  File "main.py", line 536, in main
    train(args, model, processor)
  File "main.py", line 178, in train
    evaluate_knn(args, model, test_features, train_features, processor, set_type="test")
  File "main.py", line 261, in evaluate_knn
    compute_embeddings(model, features, processor, args, verbose=False)
  File "/EE/fewshot_ED/utils.py", line 127, in compute_embeddings
    assert(tok_embeddings.shape[0]==event_feature_num)
AssertionError
 ```
使用ACE数据集能正常运行，但是使用MAVEN数据集时出现错误。
错误如上所示，最上面两行打印的是tok_embeddings.shape[0]和event_feature_num值，请问该如何修改，谢谢！

**Comment by mayubo2333** [comment]
I'm on vacation and can't get access to the code and data in the server. I will help you to solve it next week.
Just a guess, can you increase the "--max_seq_length" from 168 to 256 and have another try?

**Comment by weiSENshu** [comment]
> I'm on vacation and can't get access to the code and data in the server. I will help you to solve it next week. Just a guess, can you increase the "--max_seq_length" from 168 to 256 and have another try?

不好意思，打扰到您了，我尝试了调整max_seq_length到176，发现它可以正常运行了

**Comment by mayubo2333** [comment]
> > I'm on vacation and can't get access to the code and data in the server. I will help you to solve it next week. Just a guess, can you increase the "--max_seq_length" from 168 to 256 and have another try?
> 
> 不好意思，打扰到您了，我尝试了调整max_seq_length到176，发现它可以正常运行了

Thanks for your trying. I have updated the running script to fix this problem.
